### ISSUE TITLE
Document use case/goal: Changing the interface of a package separately from the implementation, e.g. for changing only the interface or only the implementation

### ISSUE THREAD

**Issue by infinisil** [nixpkgs-architecture/packages-modules#10]

**Comment by infinisil** [comment]
Packages currently have the interface and implementation together:
```
{ hello, enableFoo ? true }:
stdenv.mkDerivation {
  # ...
}
```

As a user I want to know what is the public API and what is internals.

**Comment by infinisil** [comment]
@edolstra says that modules aren't that great for that.

Can mark things as internal. Can use let or `internal = true`, but then still exposed.

**Comment by DavHau** [comment]
implemented in https://github.com/nixpkgs-architecture/pkgs-modules/pull/13
