### ISSUE TITLE
Present drv-parts

### ISSUE THREAD

**Issue by infinisil** [nixpkgs-architecture/packages-modules#20]
We're slowly concluding the first milestone on use cases, the next part will be looking at the potential solutions. @DavHau could you have a short presentation ready to talk about drv-parts sometime this month?

We should record this if that's okay with you.

**Comment by DavHau** [comment]
I can have something ready by the next meeting this friday.

**Comment by infinisil** [comment]
I'll try to schedule this so most people can make it. Also @DavHau agreed to have it be recorded, we can upload it to https://www.youtube.com/@nixpkgs-architecture

**Comment by infinisil** [comment]
On Matrix, everybody on the team confirmed that they can make it to this Fridays meeting, so we'll have this then :D

**Comment by infinisil** [comment]
YouTube stream: https://youtube.com/live/FmaFOlKRUKw

**Comment by infinisil** [comment]
Let's close this once we have a document describing drv-parts with a link to the presentation
