### ISSUE TITLE
Cut together the drv-parts presentation

### ISSUE THREAD

**Issue by infinisil** [nixpkgs-architecture/packages-modules#27]
https://www.youtube.com/watch?v=FmaFOlKRUKw and the rerecorded intro in https://www.youtube.com/watch?v=7D5PJwh3vug. Needed to finish #20

**Comment by infinisil** [comment]
Also publish brief meeting notes linking to it afterwards

**Comment by infinisil** [comment]
@phaer agreed to give this a try, I gave him permissions to the Nixpkgs Architecture Team YouTube channel for that.

**Comment by phaer** [comment]
Still "processing" on YouTube, 3 hours later. So let's see if I can get it done before the weekend :sweat_smile:

**Comment by phaer** [comment]
Done, see https://youtu.be/AsCvRZukX0E
